language: node_js

branches:
  only:
    - master

node_js:
  - "6"
  - "7"

services:
  - mongodb

before_script:
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com
